language: python
sudo: false
python:
    - 2.7

notifications:
    email: false

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -f /home/travis/miniconda2
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    # Travis CI-related
    #- sudo rm -rf /dev/shm
    #- sudo ln -s /run/shm /dev/shm

# Install packages
install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy six pytest
    - conda install --yes -c https://conda.anaconda.org/bokeh pytest-cov

# Run test
script:
    - py.test

after_success:
    - pip install coveralls
    - coveralls
